"""Complete CET-4 and CET-6 vocabulary data.

Format: (word, phonetic, meaning, collocations, frequency)
Frequency: "high" / "medium" / "low"
"""

CET4_WORDS = [
    # ═══ A ═══
    ("a", "/eɪ/", "art. 一(个)；每一(个)", "", "high"),
    ("abandon", "/əˈbændən/", "vt. 放弃；遗弃；抛弃", "abandon oneself to 沉溺于", "high"),
    ("ability", "/əˈbɪləti/", "n. 能力；才能", "to the best of one's ability", "high"),
    ("able", "/ˈeɪbl/", "adj. 能够的；有能力的", "be able to do", "high"),
    ("abnormal", "/æbˈnɔːml/", "adj. 反常的；异常的", "", "medium"),
    ("aboard", "/əˈbɔːd/", "adv./prep. 在船(飞机、车)上；上船", "", "medium"),
    ("about", "/əˈbaʊt/", "prep. 关于；大约", "be about to do 即将", "high"),
    ("above", "/əˈbʌv/", "prep. 在…上面；高于", "above all 首先", "high"),
    ("abroad", "/əˈbrɔːd/", "adv. 在国外；到国外", "go abroad 出国", "high"),
    ("absence", "/ˈæbsəns/", "n. 缺席；缺乏；不在", "in the absence of", "high"),
    ("absent", "/ˈæbsənt/", "adj. 缺席的；心不在焉的", "", "medium"),
    ("absolute", "/ˈæbsəluːt/", "adj. 绝对的；完全的；专制的", "", "medium"),
    ("absolutely", "/ˌæbsəˈluːtli/", "adv. 绝对地；完全地", "", "high"),
    ("absorb", "/əbˈzɔːb/", "vt. 吸收；吸引(注意力)", "be absorbed in", "high"),
    ("abstract", "/ˈæbstrækt/", "adj. 抽象的 n. 摘要", "", "medium"),
    ("abundant", "/əˈbʌndənt/", "adj. 丰富的；充裕的", "be abundant in", "medium"),
    ("abuse", "/əˈbjuːz/", "n./vt. 滥用；虐待；辱骂", "", "high"),
    ("academic", "/ˌækəˈdemɪk/", "adj. 学术的；学院的", "academic year 学年", "high"),
    ("academy", "/əˈkædəmi/", "n. 学院；研究院；专科学校", "", "medium"),
    ("accelerate", "/əkˈseləreɪt/", "v. 加速；促进", "", "medium"),
    ("accent", "/ˈæksent/", "n. 口音；腔调；重音", "", "medium"),
    ("accept", "/əkˈsept/", "v. 接受；承认；认可", "", "high"),
    ("acceptable", "/əkˈseptəbl/", "adj. 可接受的；合意的", "", "medium"),
    ("acceptance", "/əkˈseptəns/", "n. 接受；接纳；承认", "", "medium"),
    ("access", "/ˈækses/", "n. 通道；进入；使用权", "have access to", "high"),
    ("accident", "/ˈæksɪdənt/", "n. 事故；意外事件", "by accident 偶然", "high"),
    ("accidental", "/ˌæksɪˈdentl/", "adj. 意外的；偶然的", "", "low"),
    ("accommodation", "/əˌkɒməˈdeɪʃn/", "n. 住宿；膳宿；适应", "", "medium"),
    ("accompany", "/əˈkʌmpəni/", "vt. 陪伴；伴随；为…伴奏", "", "high"),
    ("accomplish", "/əˈkʌmplɪʃ/", "vt. 完成；实现；达到", "", "high"),
    ("accord", "/əˈkɔːd/", "n. 一致；协议；条约", "of one's own accord 自愿", "medium"),
    ("accordance", "/əˈkɔːdns/", "n. 一致；和谐", "in accordance with", "medium"),
    ("accordingly", "/əˈkɔːdɪŋli/", "adv. 因此；相应地；于是", "", "medium"),
    ("account", "/əˈkaʊnt/", "n. 账户；账目；描述", "take into account", "high"),
    ("accountant", "/əˈkaʊntənt/", "n. 会计师；会计人员", "", "medium"),
    ("accumulate", "/əˈkjuːmjəleɪt/", "v. 积累；积聚；堆积", "", "medium"),
    ("accuracy", "/ˈækjərəsi/", "n. 精确性；准确度", "", "medium"),
    ("accurate", "/ˈækjərət/", "adj. 准确的；精确的；正确的", "", "high"),
    ("accuse", "/əˈkjuːz/", "vt. 控告；指责；谴责", "accuse sb of", "medium"),
    ("accustomed", "/əˈkʌstəmd/", "adj. 习惯的；惯常的", "be accustomed to", "medium"),
    ("ache", "/eɪk/", "vi./n. 疼痛；酸痛", "", "medium"),
    ("achieve", "/əˈtʃiːv/", "vt. 实现；完成；达到", "", "high"),
    ("achievement", "/əˈtʃiːvmənt/", "n. 成就；成绩；完成", "", "high"),
    ("acid", "/ˈæsɪd/", "n. 酸 adj. 酸的；尖刻的", "", "medium"),
    ("acknowledge", "/əkˈnɒlɪdʒ/", "vt. 承认；确认；致谢", "", "medium"),
    ("acquaint", "/əˈkweɪnt/", "vt. 使认识；使了解", "be acquainted with", "medium"),
    ("acquaintance", "/əˈkweɪntəns/", "n. 熟人；相识的人", "", "medium"),
    ("acquire", "/əˈkwaɪə(r)/", "vt. 获得；得到；习得", "", "high"),
    ("acquisition", "/ˌækwɪˈzɪʃn/", "n. 获得；习得；收购", "", "medium"),
    ("acre", "/ˈeɪkə(r)/", "n. 英亩；大片土地", "", "low"),
    ("across", "/əˈkrɒs/", "prep./adv. 穿过；横过；在对面", "", "high"),
    ("act", "/ækt/", "v. 行动；表现；表演 n. 行为；法案", "act as 充当", "high"),
    ("action", "/ˈækʃn/", "n. 行动；行为；活动", "take action", "high"),
    ("active", "/ˈæktɪv/", "adj. 积极的；活跃的；主动的", "", "high"),
    ("activity", "/ækˈtɪvəti/", "n. 活动；活跃；行动", "", "high"),
    ("actor", "/ˈæktə(r)/", "n. 男演员；行动者", "", "high"),
    ("actress", "/ˈæktrəs/", "n. 女演员", "", "high"),
    ("actual", "/ˈæktʃuəl/", "adj. 实际的；真实的；事实上的", "", "high"),
    ("actually", "/ˈæktʃuəli/", "adv. 实际上；事实上；竟然", "", "high"),
    ("acute", "/əˈkjuːt/", "adj. 严重的；急性的；敏锐的", "", "medium"),
    ("ad", "/æd/", "n. 广告 (=advertisement)", "", "medium"),
    ("adapt", "/əˈdæpt/", "v. 适应；改编；改造", "adapt to 适应", "high"),
    ("add", "/æd/", "v. 增加；添加；补充说", "add up to 总计", "high"),
    ("addict", "/ˈædɪkt/", "n. 上瘾者 vt. 使沉溺", "be addicted to", "medium"),
    ("addition", "/əˈdɪʃn/", "n. 加；加法；增加", "in addition to", "high"),
    ("additional", "/əˈdɪʃənl/", "adj. 附加的；额外的；追加的", "", "high"),
    ("address", "/əˈdres/", "n. 地址；演说 vt. 对…讲话；处理", "", "high"),
    ("adequate", "/ˈædɪkwət/", "adj. 足够的；充分的；适当的", "", "high"),
    ("adjust", "/əˈdʒʌst/", "v. 调整；调节；适应", "adjust to", "high"),
    ("administration", "/ədˌmɪnɪˈstreɪʃn/", "n. 管理；行政；执行；政府", "", "medium"),
    ("admire", "/ədˈmaɪə(r)/", "vt. 钦佩；赞赏；羡慕", "", "high"),
    ("admission", "/ədˈmɪʃn/", "n. 准许进入；承认；入场费", "", "medium"),
    ("admit", "/ədˈmɪt/", "v. 承认；准许…进入", "admit doing", "high"),
    ("adopt", "/əˈdɒpt/", "vt. 采用；采取；收养", "", "high"),
    ("adult", "/ˈædʌlt/", "n. 成年人 adj. 成年的；成熟的", "", "high"),
    ("advance", "/ədˈvɑːns/", "v. 前进；推进；促进 n. 进步", "in advance 提前", "high"),
    ("advanced", "/ədˈvɑːnst/", "adj. 先进的；高级的；高等的", "", "high"),
    ("advantage", "/ədˈvɑːntɪdʒ/", "n. 优势；有利条件；好处", "take advantage of", "high"),
    ("adventure", "/ədˈventʃə(r)/", "n. 冒险；冒险经历；奇遇", "", "high"),
    ("advertise", "/ˈædvətaɪz/", "v. 做广告；宣传；公布", "", "medium"),
    ("advertisement", "/ədˈvɜːtɪsmənt/", "n. 广告；公告；宣传", "", "high"),
    ("advice", "/ədˈvaɪs/", "n. 忠告；建议；劝告", "take one's advice", "high"),
    ("advisable", "/ədˈvaɪzəbl/", "adj. 明智的；可取的；适当的", "", "medium"),
    ("advise", "/ədˈvaɪz/", "vt. 劝告；建议；通知", "advise sb to do", "high"),
    ("advocate", "/ˈædvəkeɪt/", "vt. 提倡；主张；拥护 n. 倡导者", "", "medium"),
    ("affair", "/əˈfeə(r)/", "n. 事务；事件；私事", "", "high"),
    ("affect", "/əˈfekt/", "vt. 影响；感动；假装", "", "high"),
    ("affection", "/əˈfekʃn/", "n. 喜爱；钟爱；感情", "", "medium"),
    ("afford", "/əˈfɔːd/", "vt. 负担得起；提供；给予", "can't afford to do", "high"),
    ("afraid", "/əˈfreɪd/", "adj. 害怕的；担心的", "be afraid of", "high"),
    ("after", "/ˈɑːftə(r)/", "prep./conj. 在…以后；在…后面", "after all 毕竟", "high"),
    ("afternoon", "/ˌɑːftəˈnuːn/", "n. 下午；午后", "", "high"),
    ("afterward(s)", "/ˈɑːftəwəd(z)/", "adv. 以后；后来；过后", "", "high"),
    ("again", "/əˈɡen/", "adv. 又；再一次；此外", "again and again", "high"),
    ("against", "/əˈɡenst/", "prep. 反对；逆着；靠着；以…为背景", "", "high"),
    ("age", "/eɪdʒ/", "n. 年龄；时代；年代", "", "high"),
    ("agency", "/ˈeɪdʒənsi/", "n. 代理处；经销处；机构", "", "high"),
    ("agenda", "/əˈdʒendə/", "n. 议程；议事日程", "", "medium"),
    ("agent", "/ˈeɪdʒənt/", "n. 代理人；代理商；经纪人", "", "medium"),
    ("aggressive", "/əˈɡresɪv/", "adj. 侵略的；好斗的；攻击性的", "", "high"),
    ("ago", "/əˈɡəʊ/", "adv. 以前；…前", "", "high"),
    ("agree", "/əˈɡriː/", "v. 同意；赞同；应允；一致", "agree with/to", "high"),
    ("agreement", "/əˈɡriːmənt/", "n. 同意；协议；协定；一致", "reach an agreement", "high"),
    ("agriculture", "/ˈæɡrɪkʌltʃə(r)/", "n. 农业；农艺；农学", "", "high"),
    ("ahead", "/əˈhed/", "adv. 在前面；向前；预先", "ahead of", "high"),
    ("aid", "/eɪd/", "n. 帮助；援助；救护 vt. 帮助", "first aid 急救", "high"),
    ("aim", "/eɪm/", "n. 目标；目的；瞄准 v. 瞄准；旨在", "aim at", "high"),
    ("air", "/eə(r)/", "n. 空气；大气；空中；神态", "by air 乘飞机", "high"),
    ("aircraft", "/ˈeəkrɑːft/", "n. 飞机；航空器；飞行器", "", "medium"),
    ("airline", "/ˈeəlaɪn/", "n. 航空公司；航线", "", "high"),
    ("airport", "/ˈeəpɔːt/", "n. 机场；航空站", "", "high"),
    ("alarm", "/əˈlɑːm/", "n. 警报；闹钟；惊恐 vt. 使惊恐", "alarm clock 闹钟", "high"),
    ("alcohol", "/ˈælkəhɒl/", "n. 酒精；酒；乙醇", "", "high"),
    ("alert", "/əˈlɜːt/", "adj. 警觉的；警惕的 n. 警报", "on the alert", "medium"),
    ("alike", "/əˈlaɪk/", "adj. 相像的 adv. 相似地", "", "medium"),
    ("alive", "/əˈlaɪv/", "adj. 活着的；有活力的；存在的", "", "high"),
    ("all", "/ɔːl/", "adj. 全部的 pron. 全部 adv. 完全", "all over 到处", "high"),
    ("alliance", "/əˈlaɪəns/", "n. 联盟；同盟；联姻", "", "medium"),
    ("allocate", "/ˈæləkeɪt/", "vt. 分配；分派；拨给", "", "medium"),
    ("allow", "/əˈlaʊ/", "vt. 允许；准许；容许", "allow sb to do", "high"),
    ("allowance", "/əˈlaʊəns/", "n. 津贴；补贴；零用钱", "", "medium"),
    ("ally", "/ˈælaɪ/", "n. 同盟国；同盟者；盟友", "", "medium"),
    ("almost", "/ˈɔːlməʊst/", "adv. 几乎；差不多", "", "high"),
    ("alone", "/əˈləʊn/", "adj./adv. 独自的(地)；单独的", "let alone 更不用说", "high"),
    ("along", "/əˈlɒŋ/", "prep./adv. 沿着；顺着；一起", "along with", "high"),
    ("alongside", "/əˌlɒŋˈsaɪd/", "prep./adv. 在…旁边；与…并肩", "", "medium"),
    ("aloud", "/əˈlaʊd/", "adv. 出声地；大声地", "", "medium"),
    ("already", "/ɔːlˈredi/", "adv. 已经；早已", "", "high"),
    ("also", "/ˈɔːlsəʊ/", "adv. 也；同样", "not only...but also", "high"),
    ("alter", "/ˈɔːltə(r)/", "v. 改变；更改；修改", "", "medium"),
    ("alternative", "/ɔːlˈtɜːnətɪv/", "n. 替代品 adj. 替代的；供选择的", "", "high"),
    ("although", "/ɔːlˈðəʊ/", "conj. 虽然；尽管；然而", "", "high"),
    ("altitude", "/ˈæltɪtjuːd/", "n. 海拔；高度；高处", "", "medium"),
    ("altogether", "/ˌɔːltəˈɡeðə(r)/", "adv. 完全；总共；总之", "", "high"),
    ("always", "/ˈɔːlweɪz/", "adv. 总是；一直；永远", "", "high"),
    ("amateur", "/ˈæmətə(r)/", "n. 业余爱好者 adj. 业余的", "", "medium"),
    ("amaze", "/əˈmeɪz/", "vt. 使惊奇；使惊愕", "", "medium"),
    ("ambassador", "/æmˈbæsədə(r)/", "n. 大使；使节；代表", "", "medium"),
    ("ambition", "/æmˈbɪʃn/", "n. 雄心；野心；抱负", "", "high"),
    ("ambitious", "/æmˈbɪʃəs/", "adj. 有雄心的；野心勃勃的", "", "medium"),
    ("ambulance", "/ˈæmbjələns/", "n. 救护车", "", "medium"),
    ("among(st)", "/əˈmʌŋ(st)/", "prep. 在…之中；在…之间", "", "high"),
    ("amount", "/əˈmaʊnt/", "n. 数量；总额 vi. 合计；等于", "a large amount of", "high"),
    ("amuse", "/əˈmjuːz/", "vt. 逗乐；使娱乐；使发笑", "", "medium"),
    ("analyse/analyze", "/ˈænəlaɪz/", "vt. 分析；分解；解析", "", "high"),
    ("analysis", "/əˈnæləsɪs/", "n. 分析；分解；解析", "", "high"),
    ("ancestor", "/ˈænsestə(r)/", "n. 祖先；祖宗；原型", "", "medium"),
    ("anchor", "/ˈæŋkə(r)/", "n. 锚；依靠 vt. 抛锚；固定", "", "medium"),
    ("ancient", "/ˈeɪnʃənt/", "adj. 古代的；古老的；年老的", "", "high"),
    ("anger", "/ˈæŋɡə(r)/", "n. 愤怒；怒火 vt. 激怒", "", "medium"),
    ("angle", "/ˈæŋɡl/", "n. 角；角度；观点；立场", "", "medium"),
    ("angry", "/ˈæŋɡri/", "adj. 愤怒的；生气的", "be angry at/with", "high"),
    ("animal", "/ˈænɪml/", "n. 动物；兽类", "", "high"),
    ("ankle", "/ˈæŋkl/", "n. 踝；脚踝", "", "medium"),
    ("anniversary", "/ˌænɪˈvɜːsəri/", "n. 周年纪念日", "", "medium"),
    ("announce", "/əˈnaʊns/", "vt. 宣布；宣告；发表；通知", "", "high"),
    ("annoy", "/əˈnɔɪ/", "vt. 使恼怒；使烦恼；打扰", "", "high"),
    ("annual", "/ˈænjuəl/", "adj. 每年的；一年一度的 n. 年刊", "", "high"),
    ("another", "/əˈnʌðə(r)/", "adj./pron. 另一个；再一个", "one after another", "high"),
    ("answer", "/ˈɑːnsə(r)/", "n. 答案 v. 回答；答复；解答", "answer for 对…负责", "high"),
    ("ant", "/ænt/", "n. 蚂蚁", "", "low"),
    ("anticipate", "/ænˈtɪsɪpeɪt/", "vt. 预期；期望；预料", "", "medium"),
    ("antique", "/ænˈtiːk/", "adj. 古老的 n. 古董；古玩", "", "medium"),
    ("anxiety", "/æŋˈzaɪəti/", "n. 焦虑；忧虑；不安；渴望", "", "high"),
    ("anxious", "/ˈæŋkʃəs/", "adj. 焦虑的；担忧的；渴望的", "be anxious about", "high"),
    ("any", "/ˈeni/", "adj./pron. 任何；任一 adv. 丝毫", "", "high"),
    ("anybody", "/ˈenibɒdi/", "pron. 任何人；无论谁", "", "high"),
    ("anyhow", "/ˈenihaʊ/", "adv. 无论如何；不管怎样", "", "medium"),
    ("anyone", "/ˈeniwʌn/", "pron. 任何人 (=anybody)", "", "high"),
    ("anything", "/ˈeniθɪŋ/", "pron. 任何事物；无论什么", "", "high"),
    ("anyway", "/ˈeniweɪ/", "adv. 无论如何；不管怎样", "", "high"),
    ("anywhere", "/ˈeniweə(r)/", "adv. 任何地方；无论何处", "", "high"),
    ("apart", "/əˈpɑːt/", "adv. 分离；分开；相隔；除了", "apart from 除…外", "high"),
    ("apartment", "/əˈpɑːtmənt/", "n. 公寓；一套房间", "", "high"),
    ("apologize", "/əˈpɒlədʒaɪz/", "vi. 道歉；赔礼", "apologize to sb for", "high"),
    ("apology", "/əˈpɒlədʒi/", "n. 道歉；歉意；辩护", "make an apology", "medium"),
    ("apparent", "/əˈpærənt/", "adj. 明显的；表面上的；显然的", "", "medium"),
    ("appeal", "/əˈpiːl/", "vi./n. 呼吁；吸引；上诉；恳求", "appeal to sb", "high"),
    ("appear", "/əˈpɪə(r)/", "vi. 出现；显得；似乎；出版", "", "high"),
    ("appearance", "/əˈpɪərəns/", "n. 外貌；外观；出现；出场", "", "high"),
    ("appetite", "/ˈæpɪtaɪt/", "n. 食欲；胃口；欲望", "", "medium"),
    ("applause", "/əˈplɔːz/", "n. 鼓掌；喝彩；欢呼", "", "medium"),
    ("apple", "/ˈæpl/", "n. 苹果", "", "high"),
    ("appliance", "/əˈplaɪəns/", "n. 电器；器具；器械", "household appliances", "medium"),
    ("applicable", "/əˈplɪkəbl/", "adj. 可适用的；合适的", "", "medium"),
    ("applicant", "/ˈæplɪkənt/", "n. 申请人；求职者", "", "medium"),
    ("application", "/ˌæplɪˈkeɪʃn/", "n. 申请；应用；应用程序", "", "high"),
    ("apply", "/əˈplaɪ/", "v. 申请；应用；涂敷；适用", "apply for", "high"),
    ("appoint", "/əˈpɔɪnt/", "vt. 任命；委派；指定；约定", "", "medium"),
    ("appointment", "/əˈpɔɪntmənt/", "n. 任命；委派；约会；预约", "make an appointment", "high"),
    ("appreciate", "/əˈpriːʃieɪt/", "vt. 欣赏；感激；领会；增值", "", "high"),
    ("approach", "/əˈprəʊtʃ/", "v. 接近 n. 方法；途径；方式", "", "high"),
    ("appropriate", "/əˈprəʊpriət/", "adj. 适当的；合适的", "", "high"),
    ("approval", "/əˈpruːvl/", "n. 批准；认可；赞成", "", "medium"),
    ("approve", "/əˈpruːv/", "v. 批准；认可；赞成；同意", "approve of", "high"),
    ("approximate", "/əˈprɒksɪmət/", "adj. 近似的；大约的 v. 接近", "", "medium"),
    ("April", "/ˈeɪprəl/", "n. 四月", "", "high"),
    ("arbitrary", "/ˈɑːbɪtrəri/", "adj. 任意的；武断的；专制的", "", "medium"),
    ("architect", "/ˈɑːkɪtekt/", "n. 建筑师；设计师", "", "medium"),
    ("architecture", "/ˈɑːkɪtektʃə(r)/", "n. 建筑学；建筑；架构", "", "high"),
    ("area", "/ˈeəriə/", "n. 面积；地区；区域；领域", "", "high"),
    ("argue", "/ˈɑːɡjuː/", "v. 争论；辩论；论证；主张", "argue about/over", "high"),
    ("argument", "/ˈɑːɡjumənt/", "n. 争论；辩论；论据；理由", "", "high"),
    ("arise", "/əˈraɪz/", "vi. 出现；产生；起床；起身", "arise from", "high"),
    ("arithmetic", "/əˈrɪθmətɪk/", "n. 算术；计算", "", "low"),
    ("arm", "/ɑːm/", "n. 手臂；支架；武器 vt. 武装", "arm in arm", "high"),
    ("army", "/ˈɑːmi/", "n. 军队；陆军；大群", "", "high"),
    ("around", "/əˈraʊnd/", "prep./adv. 在…周围；到处；大约", "", "high"),
    ("arouse", "/əˈraʊz/", "vt. 引起；唤醒；激起", "arouse one's interest", "medium"),
    ("arrange", "/əˈreɪndʒ/", "v. 安排；布置；整理；排列", "arrange for", "high"),
    ("arrangement", "/əˈreɪndʒmənt/", "n. 安排；布置；整理；协议", "", "medium"),
    ("arrest", "/əˈrest/", "vt./n. 逮捕；拘留；阻止", "", "medium"),
    ("arrival", "/əˈraɪvl/", "n. 到达；到来；抵达", "", "medium"),
    ("arrive", "/əˈraɪv/", "vi. 到达；抵达；来临", "arrive at/in", "high"),
    ("arrow", "/ˈærəʊ/", "n. 箭；箭头符号", "", "medium"),
    ("art", "/ɑːt/", "n. 艺术；美术；技术；文科", "", "high"),
    ("article", "/ˈɑːtɪkl/", "n. 文章；论文；物品；冠词", "", "high"),
    ("artificial", "/ˌɑːtɪˈfɪʃl/", "adj. 人工的；人造的；虚假的", "artificial intelligence", "high"),
    ("artist", "/ˈɑːtɪst/", "n. 艺术家；美术家；画家", "", "high"),
    ("as", "/æz/", "conj./prep. 作为；如同；当…时；因为", "as...as", "high"),
    ("ash", "/æʃ/", "n. 灰；灰烬；骨灰", "", "medium"),
    ("ashamed", "/əˈʃeɪmd/", "adj. 羞愧的；惭愧的；羞耻的", "be ashamed of", "medium"),
    ("aside", "/əˈsaɪd/", "adv. 在旁边；到一边；留出", "aside from 除了", "medium"),
    ("ask", "/ɑːsk/", "v. 问；询问；请求；要求", "ask for 要求", "high"),
    ("asleep", "/əˈsliːp/", "adj. 睡着的；熟睡的", "fall asleep 入睡", "high"),
    ("aspect", "/ˈæspekt/", "n. 方面；层面；外表", "", "high"),
    ("assemble", "/əˈsembl/", "v. 集合；收集；组装；装配", "", "medium"),
    ("assembly", "/əˈsembli/", "n. 集合；集会；装配；议会", "", "medium"),
    ("assess", "/əˈses/", "vt. 评估；评定；估价", "", "high"),
    ("asset", "/ˈæset/", "n. 资产；财产；优点；有价值的人", "", "high"),
    ("assign", "/əˈsaɪn/", "vt. 分配；指派；布置；指定", "", "medium"),
    ("assignment", "/əˈsaɪnmənt/", "n. 任务；作业；分配；指派", "", "medium"),
    ("assist", "/əˈsɪst/", "v. 帮助；协助；援助", "", "high"),
    ("assistance", "/əˈsɪstəns/", "n. 帮助；援助；支持", "", "medium"),
    ("assistant", "/əˈsɪstənt/", "n. 助手；助理；助教", "", "high"),
    ("associate", "/əˈsəʊʃieɪt/", "vt. 联系；联想 n. 同事；伙伴", "associate with", "high"),
    ("association", "/əˌsəʊʃiˈeɪʃn/", "n. 协会；社团；联系；联想", "", "high"),
    ("assume", "/əˈsjuːm/", "vt. 假定；假设；承担；呈现", "", "high"),
    ("assumption", "/əˈsʌmpʃn/", "n. 假定；假设；承担", "", "medium"),
    ("assure", "/əˈʃʊə(r)/", "vt. 使确信；向…保证；确保", "", "medium"),
    ("astonish", "/əˈstɒnɪʃ/", "vt. 使惊讶；使震惊", "", "medium"),
    ("astronaut", "/ˈæstrənɔːt/", "n. 宇航员；太空人", "", "medium"),
    ("athlete", "/ˈæθliːt/", "n. 运动员；体育家", "", "high"),
    ("atmosphere", "/ˈætməsfɪə(r)/", "n. 大气；气氛；氛围；环境", "", "high"),
    ("atom", "/ˈætəm/", "n. 原子；微粒", "", "medium"),
    ("attach", "/əˈtætʃ/", "vt. 附上；贴上；系上；使附属", "be attached to", "high"),
    ("attack", "/əˈtæk/", "v./n. 攻击；袭击；抨击", "", "high"),
    ("attain", "/əˈteɪn/", "vt. 达到；获得；实现", "", "medium"),
    ("attempt", "/əˈtempt/", "n./vt. 尝试；试图；企图", "make an attempt", "high"),
    ("attend", "/əˈtend/", "v. 参加；出席；照料；注意", "attend to", "high"),
    ("attention", "/əˈtenʃn/", "n. 注意；注意力；关心；关注", "pay attention to", "high"),
    ("attitude", "/ˈætɪtjuːd/", "n. 态度；看法；姿势", "attitude to/towards", "high"),
    ("attract", "/əˈtrækt/", "vt. 吸引；引起；诱惑", "", "high"),
    ("attraction", "/əˈtrækʃn/", "n. 吸引力；吸引人的事物", "", "medium"),
    ("attractive", "/əˈtræktɪv/", "adj. 有吸引力的；迷人的；漂亮的", "", "high"),
    ("attribute", "/əˈtrɪbjuːt/", "vt. 把…归因于 n. 属性；特性", "attribute to", "medium"),
    ("audience", "/ˈɔːdiəns/", "n. 观众；听众；读者；受众", "", "high"),
    ("August", "/ˈɔːɡəst/", "n. 八月", "", "high"),
    ("aunt", "/ɑːnt/", "n. 姑妈；姨妈；伯母；婶婶", "", "high"),
    ("author", "/ˈɔːθə(r)/", "n. 作者；作家；著者", "", "high"),
    ("authority", "/ɔːˈθɒrəti/", "n. 权威；权力；当局；官方", "have authority to do", "high"),
    ("auto", "/ˈɔːtəʊ/", "n. 汽车 (automobile的缩写)", "", "medium"),
    ("automatic", "/ˌɔːtəˈmætɪk/", "adj. 自动的；无意识的 n. 自动装置", "", "high"),
    ("autumn", "/ˈɔːtəm/", "n. 秋天；秋季", "", "high"),
    ("available", "/əˈveɪləbl/", "adj. 可获得的；可用的；有空的", "", "high"),
    ("avenue", "/ˈævənjuː/", "n. 林荫道；大街；途径", "", "medium"),
    ("average", "/ˈævərɪdʒ/", "n./adj. 平均(的)；普通的(地)", "on average", "high"),
    ("avoid", "/əˈvɔɪd/", "vt. 避免；避开；防止", "avoid doing", "high"),
    ("await", "/əˈweɪt/", "vt. 等待；等候；期待", "", "medium"),
    ("awake", "/əˈweɪk/", "v. 醒；唤醒 adj. 醒着的", "", "medium"),
    ("award", "/əˈwɔːd/", "n. 奖；奖品；奖金 vt. 授予", "", "high"),
    ("aware", "/əˈweə(r)/", "adj. 意识到的；知道的；明白的", "be aware of", "high"),
    ("away", "/əˈweɪ/", "adv. 离开；远离；去别处", "right away 立刻", "high"),
    ("awful", "/ˈɔːfl/", "adj. 可怕的；糟糕的；极坏的", "", "high"),
    ("awkward", "/ˈɔːkwəd/", "adj. 尴尬的；笨拙的；棘手的", "", "medium"),
]
# Will continue with more sections in the next iteration
